# Generated by Django 5.1.7 on 2025-03-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stockId', models.AutoField(db_column='stk_id', primary_key=True, serialize=False)),
                ('stockName', models.CharField(db_column='stk_name', max_length=50, unique=True)),
                ('scriptCode', models.CharField(db_column='stk_script_code', max_length=20, unique=True)),
                ('price', models.DecimalField(db_column='stk_price', decimal_places=2, max_digits=9)),
                ('createdOn', models.DateTimeField(db_column='createdOn')),
                ('updatedOn', models.DateTimeField(db_column='updatedOn')),
            ],
        ),
    ]
