# Generated by Django 5.1.7 on 2025-03-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, db_column='createdOn'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True, db_column='updatedOn'),
        ),
    ]
