# Generated by Django 5.1.7 on 2025-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_stocks_createdon_alter_stocks_updatedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(db_column='usr_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='usr_name', max_length=100)),
                ('emailId', models.EmailField(db_column='usr_email_id', max_length=254, unique=True)),
                ('password', models.CharField(db_column='usr_password', max_length=30)),
                ('createdOn', models.DateTimeField(auto_now_add=True, db_column='createdOn')),
                ('updatedOn', models.DateTimeField(auto_now=True, db_column='updatedOn')),
            ],
        ),
    ]
