# Generated by Django 5.1.7 on 2025-03-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_stocks_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolioId', models.AutoField(db_column='pof_id', primary_key=True, serialize=False)),
                ('stockQty', models.IntegerField(db_column='pof_stk_qty')),
                ('transactionType', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], db_column='pof_tran_type', max_length=1)),
                ('transactionPrice', models.DecimalField(db_column='pof_tran_price', decimal_places=2, max_digits=9)),
                ('transactionDate', models.DateTimeField(db_column='pof_tran_date')),
                ('createdOn', models.DateTimeField(auto_now_add=True, db_column='createdOn')),
                ('updatedOn', models.DateTimeField(auto_now=True, db_column='updatedOn')),
                ('stockId', models.ForeignKey(db_column='pof_stk_id', on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock')),
                ('userId', models.ForeignKey(db_column='pof_usr_id', on_delete=django.db.models.deletion.CASCADE, to='portfolio.user')),
            ],
        ),
    ]
