# Generated by Django 5.1.7 on 2025-03-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='stockId',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='userId',
            new_name='user',
        ),
    ]
