# Generated by Django 5.1.7 on 2025-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_stockid_portfolio_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='stock',
            new_name='stockId',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='runningQtyAfter',
            field=models.IntegerField(db_column='pof_run_qty_after', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='runningQtyBefore',
            field=models.IntegerField(db_column='pof_run_qty_before', default=0),
            preserve_default=False,
        ),
    ]
