# Generated by Django 5.1.7 on 2025-04-15 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_trade_delete_portfolio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='scriptCode',
            new_name='script_code',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stockId',
            new_name='stock_id',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stockName',
            new_name='stock_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updatedOn',
        ),
        migrations.AddField(
            model_name='stock',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_column='updated_on'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='stock_price_positive_constraint'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(condition=models.Q(('trade_price__gt', 0)), name='trade_price_positive_constraint'),
        ),
    ]
