# Generated by Django 5.1.7 on 2025-04-15 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_scriptcode_stock_script_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailId',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updatedOn',
        ),
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_column='updated_on'),
        ),
    ]
